---
- name: Create virtual environment
  block:
    - name: Ensure venv parent directory exists
      file:
        path: "{{ qlora_venv_path | dirname }}"
        state: directory
        mode: "0755"
      become: yes

    - name: Create Python {{ python_version }} virtual environment
      command: "/usr/bin/python{{ python_version }} -m venv {{ qlora_venv_path }}"
      args:
        creates: "{{ qlora_venv_path }}/bin/activate"
      become: yes

    - name: Install latest pip & wheel inside venv
      command: "{{ qlora_venv_path }}/bin/pip install --upgrade pip wheel"
      become: yes

- name: Install Python Torch dependencies in venv
  shell: |
    {{ qlora_venv_path }}/bin/pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
  args:
    chdir: "{{ work_dir }}"
  register: python_torch_dependencies
  become: yes

- debug:
    var: python_torch_dependencies.stdout_lines

- name: Install Python dependencies in venv
  shell: |
    {{ qlora_venv_path }}/bin/pip install transformers peft datasets bitsandbytes accelerate sentence-transformers llama-index llama-index-llms-bedrock-converse boto3 python-docx minio chromadb tqdm
  args:
    chdir: "{{ work_dir }}"
  register: python_dependencies
  become: yes

- debug:
    var: python_dependencies.stdout_lines